spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver # Enable to ORACLE
        #driverClassName: com.mysql.cj.jdbc.Driver # mysql
        # url: ${BD_URL:jdbc:mysql://192.168.79.66/certificaciones} # mysql
        url: ${BD_URL:jdbc:oracle:thin:@//100.100.1.101:1521/PBAS}
        username: RNPSOLICITUD
        password: R3NAP7s3
        # driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver #Enable to SQL SERVER
        initialization-mode: always
        
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect #Enable to Oracle
        show-sql: true
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

        properties:
            hibernate:
              format_sql: true
              use_sql_comments: true
              synonyms: true
              c3p0: 
                max_size: 5
server:
    port: 5007